---
title: "p8105_hw1_tk2886"
author: "Tanvir Khan"
date: 2021-09-24
output: github_document
---


```{r setup, include=FALSE}
library(tidyverse)
```

#### QUESTION 1 
```{r}
set.seed(12345)
mydataframe = tibble(
  random_sample = rnorm(10),
  logical_vec = random_sample > 0,
  char_vec = c("My", "name", "is", "Tanvir", "Khan", "and", "I", "like", "the", "Lakers"),
  fac_vec = factor(c("single", "single", "single", "single", "married", "married", "married", "divorced", "divorced", "divorced")),
)

knitr::kable(mydataframe)
```

```{r Mean of each vector}
ransample_mean = mean(pull(mydataframe, random_sample))
logicalvec_mean = mean(pull(mydataframe, logical_vec))
charvec_mean = mean(pull(mydataframe, char_vec))
facvec_mean = mean(pull(mydataframe, fac_vec))
```


```{r Attempting to convert character, logical, factor vector into numeric}
numeric_char = as.numeric(factor(pull(mydataframe,char_vec)))
numeric_logv = as.numeric(pull(mydataframe, logical_vec))
numeric_fac = as.numeric(pull(mydataframe, fac_vec))
```


```{r Calculating the mean of the new conversion numbers}
mean_numchar = mean(numeric_char)
mean_numlogic = mean(numeric_logv)
mean_numfactor = mean(numeric_fac)
```





#### Question 2
```{r}
data("penguins", package = "palmerpenguins")

skimr::skim(penguins)
names(penguins)

## The important variables are bill_length_mm, bill_depth_mm, flipper_length_mm, and body_mass_g. Also, sex, year, species, and island are important variables. 
## There is 344 rows and 8 columns 
## The mean of the flipper length is 201.

```

```{r Creating scatterplot}
ggplot(penguins, aes(x = bill_length_mm, y = flipper_length_mm, color = species)) +
  geom_point(size = 2, shape = 23)
```

```{r Saving ggplot as PDF}
ggsave("scatter_plot.pdf", plot = last_plot(), height = 4, width = 6)
```


