p8105\_hw1\_tk2886
================
Tanvir Khan
2021-09-24

## QUESTION 1

``` r
set.seed(12345)

mydataframe <- tibble(
                  random_sample = rnorm(10),
                  logical_vec = c(random_sample > 0),
                  char_vec = c("My", "name", "is", "Tanvir", "Khan", "and", "I", "like","the", "Lakers"),
                  fac_vec = factor(c("single", "single", "single", "single", "married", "married", "married", "divorced", "divorced", "divorced")),
)

knitr::kable(mydataframe)
```

| random\_sample | logical\_vec | char\_vec | fac\_vec |
|---------------:|:-------------|:----------|:---------|
|      0.5855288 | TRUE         | My        | single   |
|      0.7094660 | TRUE         | name      | single   |
|     -0.1093033 | FALSE        | is        | single   |
|     -0.4534972 | FALSE        | Tanvir    | single   |
|      0.6058875 | TRUE         | Khan      | married  |
|     -1.8179560 | FALSE        | and       | married  |
|      0.6300986 | TRUE         | I         | married  |
|     -0.2761841 | FALSE        | like      | divorced |
|     -0.2841597 | FALSE        | the       | divorced |
|     -0.9193220 | FALSE        | Lakers    | divorced |

``` r
rnorm_mean = mean(pull(mydataframe, random_sample))
logicalvec_mean = mean(pull(mydataframe, logical_vec))
charvec_mean = mean(pull(mydataframe, char_vec))
## Warning in mean.default(pull(mydataframe, char_vec)): argument is not numeric or
## logical: returning NA
facvec_mean = mean(pull(mydataframe, fac_vec))
## Warning in mean.default(pull(mydataframe, fac_vec)): argument is not numeric or
## logical: returning NA
```

When I take the mean of the random sample of size 10 variable from a
standard Normal distribution, the mean function works on this and it
gives me a value. This works because it contains numeric value. I can
take the mean of a numeric value.

When I take the mean of the logical vector, the mean functions work on
this logical vector even though that does not make sense. If someone
looks at the data frame they will see that the logical vector in my
dataframe displays True and False. The True is being converted to 1 and
False is being converted to 0. I have four True out of 10 and that is
0.4 which is the same value as the mean function is outputting.

When I take the mean of the character vector and factor vector, the
console output is displaying a warning message that states the argument
is not numeric or logical: “Returning NA”. This makes sense for the
character vector since I can not take the mean of a character vector
which does not have numeric values. The factor vector is not numeric or
logical.

``` r
numeric_char = as.numeric(pull(mydataframe,char_vec))
## Warning: NAs introduced by coercion
numeric_logv = as.numeric(pull(mydataframe, logical_vec))
numeric_fac = as.numeric(pull(mydataframe, fac_vec))
```

When I attempted to convert the character variables in the character
vector, NA is returned. If I understand correctly, the values in the
character value are characters/letters and we can’t convert words or
letters to numbers. When I convert the logical variables from the
logical vector to numeric, it displays 0 and 1. 0’s indicate True and
1’s indicate False. When I convert factor variables in the factor vector
to numeric, 3,2,1 are displayed. I believe that the 3,2,1 are numeric
codes for the three different levels of the factor.

``` r
numeric_character = as.numeric(factor(pull(mydataframe, char_vec)))
```

``` r
mean_numchar = mean(numeric_char)
mean_numlogic = mean(numeric_logv)
mean_numfactor = mean(numeric_fac)
```

When I take the mean of the converted character vector, it gives me NA
because I did not successfully convert character vector to numeric
variables. When I take the mean of the numeric converted logical vector,
I get the mean of 0.4 because R is handling True’s as 0 and False as 1.
When I take the mean of the numeric converted factor vector, I get the
mean of 2.1 which is the mean of the different levels of the factor
vector.

## QUESTION 2

``` r
data("penguins", package = "palmerpenguins")
skimr::skim(penguins)
```

|                                                  |          |
|:-------------------------------------------------|:---------|
| Name                                             | penguins |
| Number of rows                                   | 344      |
| Number of columns                                | 8        |
| \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_   |          |
| Column type frequency:                           |          |
| factor                                           | 3        |
| numeric                                          | 5        |
| \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_ |          |
| Group variables                                  | None     |

Data summary

**Variable type: factor**

| skim\_variable | n\_missing | complete\_rate | ordered | n\_unique | top\_counts                 |
|:---------------|-----------:|---------------:|:--------|----------:|:----------------------------|
| species        |          0 |           1.00 | FALSE   |         3 | Ade: 152, Gen: 124, Chi: 68 |
| island         |          0 |           1.00 | FALSE   |         3 | Bis: 168, Dre: 124, Tor: 52 |
| sex            |         11 |           0.97 | FALSE   |         2 | mal: 168, fem: 165          |

**Variable type: numeric**

| skim\_variable      | n\_missing | complete\_rate |    mean |     sd |     p0 |     p25 |     p50 |    p75 |   p100 | hist  |
|:--------------------|-----------:|---------------:|--------:|-------:|-------:|--------:|--------:|-------:|-------:|:------|
| bill\_length\_mm    |          2 |           0.99 |   43.92 |   5.46 |   32.1 |   39.23 |   44.45 |   48.5 |   59.6 | ▃▇▇▆▁ |
| bill\_depth\_mm     |          2 |           0.99 |   17.15 |   1.97 |   13.1 |   15.60 |   17.30 |   18.7 |   21.5 | ▅▅▇▇▂ |
| flipper\_length\_mm |          2 |           0.99 |  200.92 |  14.06 |  172.0 |  190.00 |  197.00 |  213.0 |  231.0 | ▂▇▃▅▂ |
| body\_mass\_g       |          2 |           0.99 | 4201.75 | 801.95 | 2700.0 | 3550.00 | 4050.00 | 4750.0 | 6300.0 | ▃▇▆▃▂ |
| year                |          0 |           1.00 | 2008.03 |   0.82 | 2007.0 | 2007.00 | 2008.00 | 2009.0 | 2009.0 | ▇▁▇▁▇ |

1.  The important variables are *species, island, bill\_length\_mm,
    bill\_depth\_mm, flipper\_length\_mm, body\_mass\_g, sex, year*.
2.  The unique **species** in the penguins data table are *Adelie,
    Gentoo, Chinstrap*.
3.  The unique **island** in the penguins data table are *Torgersen,
    Biscoe, Dream*.
4.  The unique **years** in the penguins data table are *2007, 2008,
    2009*.
5.  The **sex** in the penguins data table are *male, female*.
6.  The mean of the **bill length** is *43.92* and the standard
    deviation of the bill length is *5.46*.
7.  The mean of the **bill depth** is *17.15* and the standard deviation
    of the bill depth is *1.97*.
8.  The mean of the **body mass** is *4201.75* and the standard
    deviation of the body mass is *801.95*.
9.  There is *344* **rows** in this data table. There is *8* **columns**
    in this data table.
10. The mean of the **flipper length** is *201* and the standard
    deviation of the flipper lenght is *14*.

``` r
penguin_scatterplot <- ggplot(penguins, aes(x = bill_length_mm, y = flipper_length_mm, color = species)) +
  geom_point(size = 2, shape = 23)

penguin_scatterplot
```

    ## Warning: Removed 2 rows containing missing values (geom_point).

![](p8105_hw1_tk2886_files/figure-gfm/Creating%20scatterplot-1.png)<!-- -->

``` r
ggsave("scatter_plot.pdf", plot = penguin_scatterplot, height = 4, width = 6)
```

    ## Warning: Removed 2 rows containing missing values (geom_point).
